name: harvest_signal
description: HarvestSignal shows currently in-season fresh produces in your area

dependencies:
  flutter:
    sdk: flutter

  location: ^1.1.7
  google_maps_webservice: ^0.0.3
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/load.gif

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700


